name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        
    - name: Publish .NET Core Project
      run: dotnet publish MickeyUtilityG/MickeyUtilityG/MickeyUtilityG.csproj -c Release -o release --nologo
    
    - name: Change base-tag in index.html from / to MickeyUtilityG
      run: sed -i 's/<base href="\/" \/>/<base href="\/MickeyUtilityG\/" \/>/g' release/wwwroot/index.html
    
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: release/wwwroot

    - name: Checkout gh-pages
      uses: actions/checkout@v2
      with:
        ref: gh-pages
        
    - name: Update appsettings.json with secrets
      run: |
        sed -i 's/PLACEHOLDER_GOOGLE_CLIENT_ID/${{ secrets.GOOGLE_CLIENT_ID }}/g' appsettings.json
        sed -i 's/PLACEHOLDER_GOOGLE_CLIENT_SECRET/${{ secrets.GOOGLE_CLIENT_SECRET }}/g' appsettings.json
        sed -i 's/PLACEHOLDER_GOOGLE_SPREADSHEET_ID/${{ secrets.GOOGLE_SPREADSHEET_ID }}/g' appsettings.json
        
    - name: Commit updated appsettings.json
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add appsettings.json
        git commit -m "Update appsettings.json with secrets" || echo "No changes to commit"
        git push