name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  deploy-to-github-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '8.0.x'
        
    - name: Publish .NET Core Project
      run: dotnet publish MickeyUtilityG/MickeyUtilityG/MickeyUtilityG.csproj -c Release -o release --nologo
    
    - name: Change base-tag in index.html from / to MickeyUtilityG
      run: sed -i 's/<base href="\/" \/>/<base href="\/MickeyUtilityG\/" \/>/g' release/wwwroot/index.html
    
    - name: Add .nojekyll file
      run: touch release/wwwroot/.nojekyll
      
    - name: Create config.js
      run: |
        echo "window.config = {" > release/wwwroot/config.js
        echo "  googleClientId: '${{ secrets.GOOGLE_CLIENT_ID }}'," >> release/wwwroot/config.js
        echo "  googleClientSecret: '${{ secrets.GOOGLE_CLIENT_SECRET }}'," >> release/wwwroot/config.js
        echo "  googleSpreadsheetId: '${{ secrets.GOOGLE_SPREADSHEET_ID }}'" >> release/wwwroot/config.js
        echo "};" >> release/wwwroot/config.js
      
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: release/wwwroot